name: Run code quality checks

on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[quality]
    - name: Check quality
      run: |
        ruff check examples tests src utils scripts
        ruff format examples tests src utils scripts --check

  check_repository_consistency:
    runs-on: ubuntu-latest
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[quality]
    - name: Check quality
      run: |
        python utils/check_copies.py
        python utils/check_dummies.py
        make deps_table_check_updated

env:
  PIP_INDEX_URL: http://localhost:8629/2024-01-10
  UV_INDEX_URL: http://localhost:8629/2024-01-10
