name: Run Torch dependency tests

on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_torch_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install torch torchvision torchaudio
        pip install pytest
    - name: Check for soft dependencies
      run: |
        pytest tests/others/test_dependencies.py

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2024-01-19
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2024-01-19
